# Generated by Django 3.1.7 on 2021-06-03 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankbranches',
            name='address',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='bankbranches',
            name='bank_id',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='bankbranches',
            name='bank_name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='bankbranches',
            name='branch',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='bankbranches',
            name='city',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='bankbranches',
            name='district',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='bankbranches',
            name='ifsc',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='bankbranches',
            name='state',
            field=models.CharField(max_length=500),
        ),
    ]
